version: "3.9"

services:

  web:
    tty: true
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    networks: 
      - backend
    volumes:
      - ".:/app"
         # path to your .env file

networks:
  backend:
    driver: bridge
